version: '3.8'

services:
  light-taskboard:
    build: .
    container_name: light-taskboard
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - VIEWER_PASSWORD=${VIEWER_PASSWORD:-viewer123}
      - SESSION_SECRET=${SESSION_SECRET:-default_session_secret}
    volumes:
      - ./data:/app/data
      - ./tasks.db:/app/tasks.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
